# Generated by Django 5.2.6 on 2025-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_material", "0001_create_issue_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueline",
            name="from_waste",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issueline",
            name="qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="issueline",
            name="stock_at_issue",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
