# Generated by Django 5.2.6 on 2025-11-03 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category_master", "0002_remove_categorymaster_texas_overhead_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=100)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "breadth",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sqmt",
                    models.DecimalField(
                        decimal_places=6, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "stitching",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "finishing",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "packaging",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="category_master.categorymaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Size Master",
                "verbose_name_plural": "Size Masters",
            },
        ),
    ]
