# Generated by Django 5.2.6 on 2025-11-03 09:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_alter_componentmaster_cost_per_unit_and_more"),
        ("size_master", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sizemaster",
            options={
                "ordering": ["component__name", "size"],
                "verbose_name": "Size Master",
                "verbose_name_plural": "Size Masters",
            },
        ),
        migrations.RemoveField(
            model_name="sizemaster",
            name="category",
        ),
        migrations.AddField(
            model_name="sizemaster",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the component this size belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="components.componentmaster",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="breadth",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Breadth in units (decimal allowed).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Breadth",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="finishing",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Finishing",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="length",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Length in units (decimal allowed).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="packaging",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Packaging",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="size",
            field=models.CharField(max_length=100, verbose_name="Size name"),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="sqmt",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.0"),
                editable=False,
                help_text="Automatically calculated as Length × Breadth.",
                max_digits=12,
                verbose_name="SqMT",
            ),
        ),
        migrations.AlterField(
            model_name="sizemaster",
            name="stitching",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stitching",
            ),
        ),
        migrations.AddIndex(
            model_name="sizemaster",
            index=models.Index(fields=["size"], name="size_master_size_15656c_idx"),
        ),
        migrations.AddIndex(
            model_name="sizemaster",
            index=models.Index(
                fields=["component"], name="size_master_compone_e302dd_idx"
            ),
        ),
    ]
