# Generated by Django 5.2.6 on 2025-11-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_alter_componentmaster_cost_per_unit_and_more"),
        (
            "size_master",
            "0002_alter_sizemaster_options_remove_sizemaster_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizemaster",
            name="component",
            field=models.ForeignKey(
                help_text="Select the component this size belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="components.componentmaster",
            ),
        ),
    ]
