# Generated by Django 5.2.6 on 2025-11-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master", "0005_remove_categorymaster_europe_retail_and_more"),
        ("size_master", "0003_alter_sizemaster_component"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sizemaster",
            options={
                "ordering": ["category__name", "size"],
                "verbose_name": "Size Master",
                "verbose_name_plural": "Size Masters",
            },
        ),
        migrations.RemoveIndex(
            model_name="sizemaster",
            name="size_master_compone_e302dd_idx",
        ),
        migrations.RemoveField(
            model_name="sizemaster",
            name="component",
        ),
        migrations.AddField(
            model_name="sizemaster",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the Category (from Category_Master(New)) this size belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="category_master.categorymasternew",
            ),
        ),
        migrations.AddIndex(
            model_name="sizemaster",
            index=models.Index(
                fields=["category"], name="size_master_categor_f018ab_idx"
            ),
        ),
    ]
