# Generated by Django 5.2.6 on 2025-11-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master_new", "0002_remove_categorysize_value"),
        ("size_master", "0004_alter_sizemaster_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizemaster",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the Category (from Category_Master(New)) this size belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_entries",
                to="category_master_new.category",
            ),
        ),
    ]
