# Generated by Django 5.2.6 on 2025-11-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category_master_new", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorysize",
            name="value",
        ),
    ]
