# Generated by Django 5.2.6 on 2025-11-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master_new", "0002_remove_categorysize_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="gf_percent",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=8, verbose_name="GF (%)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="import_percent",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=8, verbose_name="Import (%)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="new_tariff_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="New Tariff (%)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="reciprocal_tariff_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="Recip. Tariff (%)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ship_us_percent",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=8, verbose_name="Ship US (%)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="shipping_inr",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Shipping (INR)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="texas_buying_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="Texas Buying (%)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="texas_retail_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="Texas Retail (%)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="tx_to_us_percent",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=8, verbose_name="TX→US (%)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="us_wholesale_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=8,
                verbose_name="US Wholesale (%)",
            ),
        ),
        migrations.AddField(
            model_name="categorysize",
            name="finishing_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Finishing Cost",
            ),
        ),
        migrations.AddField(
            model_name="categorysize",
            name="packaging_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Packaging Cost",
            ),
        ),
        migrations.AddField(
            model_name="categorysize",
            name="stitching_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Stitching Cost",
            ),
        ),
    ]
