# Generated by Django 5.2.6 on 2025-11-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "category_master_new",
            "0003_category_gf_percent_category_import_percent_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="categorysize",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Category Size",
                "verbose_name_plural": "Category Sizes",
            },
        ),
    ]
