# Generated by Django 5.2.6 on 2025-11-01 11:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0006_alter_componentmaster_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gf_overhead",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="GF Overhead",
                    ),
                ),
                (
                    "texas_overhead",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Texas Overhead",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        help_text="Select the Component Master entry this category belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="components.componentmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Master",
                "verbose_name_plural": "Category Masters",
                "ordering": ["-created_at"],
            },
        ),
    ]
