# Generated by Django 5.2.6 on 2025-11-01 11:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymaster",
            name="texas_overhead",
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="europe_retail",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Europe Retail",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="europe_wholesale",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Europe Whole Sale",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="import_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Import",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="india_retail",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="India Retail",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="new_tariff",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Tariff percentage or absolute value as per your business model.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="New Tariff",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="reciprocal_tariff",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Reciprocal Tariff",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="shipping_cost_europe",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Shipping Cost Europe",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="shipping_cost_india",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Shipping Cost India",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="shipping_cost_usa",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Shipping Cost USA",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="texas_buying_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Texas Buying Cost",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="texas_to_us_selling_inr",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Texas to US Selling Price (INR)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="texas_to_us_selling_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Texas to US Selling Price (Dollar)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="us_retail",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="US Retail",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="usa_buying_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="USA Buying Cost",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="usa_wholesale",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="USA Whole Sale",
            ),
        ),
    ]
