# Generated by Django 5.2.6 on 2025-11-05 08:00
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def populate_categorymasternew(apps, schema_editor):
    """
    Create CategoryMasterNew rows for every distinct component_id referenced by
    existing CategoryMaster rows. We reuse the same primary key (component_id)
    to make the FK switch safe.
    """
    CategoryMaster = apps.get_model("category_master", "CategoryMaster")
    CategoryMasterNew = apps.get_model("category_master", "CategoryMasterNew")
    ComponentMaster = apps.get_model("components", "ComponentMaster")

    # Get distinct referenced ids from CategoryMaster table
    # Note: use the ORM to remain DB-agnostic
    referenced_ids = (
        CategoryMaster.objects
        .exclude(component__isnull=True)
        .values_list("component", flat=True)
        .distinct()
    )

    for comp_id in referenced_ids:
        if comp_id is None:
            continue
        # If already exists, skip
        if CategoryMasterNew.objects.filter(pk=comp_id).exists():
            continue
        # Try to read a sensible name from ComponentMaster (if available)
        try:
            comp = ComponentMaster.objects.get(pk=comp_id)
            name = getattr(comp, "name", str(comp))
        except Exception:
            # Fallback placeholder name
            name = f"component-{comp_id}"
        # Create new CategoryMasterNew row with same PK so the FK can be validated later
        CategoryMasterNew.objects.create(id=comp_id, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("category_master", "0002_remove_categorymaster_texas_overhead_and_more"),
        # No dependency on components needed here; ORM lookup will still work because
        # components migrations should be applied in the normal migration order.
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMasterNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide from dropdowns",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category (master list)",
                "verbose_name_plural": "Category (master lists)",
                "ordering": ["name"],
            },
        ),
        # Populate the new table from existing references BEFORE we change the FK.
        migrations.RunPython(populate_categorymasternew, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="categorymaster",
            name="component",
            field=models.ForeignKey(
                help_text="Select the Category Master New entry this category belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="category_master.categorymasternew",
            ),
        ),
    ]
