# Generated by Django 5.2.6 on 2025-11-06 04:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master", "0004_populate_categorymasternew_from_components"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymaster",
            name="europe_retail",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="europe_wholesale",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="india_retail",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="shipping_cost_europe",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="shipping_cost_india",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="shipping_cost_usa",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="texas_to_us_selling_inr",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="texas_to_us_selling_usd",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="us_retail",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="usa_buying_cost",
        ),
        migrations.RemoveField(
            model_name="categorymaster",
            name="usa_wholesale",
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="shipping_cost_inr",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Shipping cost in INR.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Shipping Cost (INR)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="shipping_us",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Shipping cost (US) as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Shipping US (%)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="texas_retail",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Texas Retail as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Texas Retail (%)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="texas_to_us_selling_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Texas to US Selling Cost as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Texas → US Selling Cost (%)",
            ),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="us_wholesale_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter US Wholesale Margin as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="US Wholesale Margin (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="component",
            field=models.ForeignKey(
                help_text="Select the category this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="category_master.categorymasternew",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="gf_overhead",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter GF Overhead as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="GF Overhead (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="import_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Import cost as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Import (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="new_tariff",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter New Tariff as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="New Tariff (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="reciprocal_tariff",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Reciprocal Tariff as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Reciprocal Tariff (%)",
            ),
        ),
        migrations.AlterField(
            model_name="categorymaster",
            name="texas_buying_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Enter Texas Buying Cost as a percentage (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Texas Buying Cost (%)",
            ),
        ),
    ]
