# Generated by Django 5.2.6 on 2025-10-13 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="True for group chats (global room or named groups)",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly name for group threads",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="chat_threads", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
