# Generated by Django 5.2.6 on 2025-09-29 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0002_vendor_address_vendor_email_vendor_mobile_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("m", "Meters"),
                            ("cm", "Centimeters"),
                            ("ft", "Feet"),
                        ],
                        default="m",
                        max_length=5,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in chosen unit (e.g., 1.20)",
                        max_digits=7,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current stock in chosen unit",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fabrics",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
    ]
