# Generated by Django 5.2.6 on 2025-09-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0001_initial"),
        ("vendors", "0002_vendor_address_vendor_email_vendor_mobile_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        default="pcs", help_text="Unit (e.g., pcs, set)", max_length=20
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current stock in unit",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate per unit", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessories",
                        to="vendors.vendor",
                    ),
                ),
            ],
        ),
    ]
