# Generated by Django 5.2.6 on 2025-09-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0002_accessory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=200)),
                ("unit", models.CharField(default="m", max_length=5)),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantity of fabric consumed (in chosen unit)",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate (per unit) if needed",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printeds",
                        to="rawmaterials.fabric",
                    ),
                ),
            ],
        ),
    ]
