# Generated by Django 5.2.6 on 2025-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0003_printed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="fabric",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="printed",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="accessory",
            name="stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Current stock in unit",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Current stock in chosen unit",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="printed",
            name="unit",
            field=models.CharField(
                choices=[("m", "Meters"), ("cm", "Centimeters"), ("ft", "Feet")],
                default="m",
                max_length=5,
            ),
        ),
    ]
