# Generated by Django 5.2.6 on 2025-10-03 07:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0004_alter_accessory_options_alter_fabric_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Rate per unit",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Rate per unit",
                max_digits=12,
            ),
        ),
    ]
