# Generated by Django 5.2.6 on 2025-10-03 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0005_fabric_rate_alter_accessory_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="printed",
            name="stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Current stock of printed product in chosen unit",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="printed",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Quantity of fabric consumed (in chosen unit) when producing this printed item",
                max_digits=12,
            ),
        ),
    ]
