# Generated by Django 5.2.6 on 2025-10-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0002_update_fabric_fields"),
        ("rawmaterials", "0006_printed_stock_alter_printed_quantity_used"),
    ]

    operations = []
