# Generated by Django 5.2.6 on 2025-10-30 07:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0007_merge_20251030_1230"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabric",
            name="unit",
        ),
        migrations.AlterField(
            model_name="fabric",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per unit (per meter)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="fabric_width",
            field=models.DecimalField(
                decimal_places=2, help_text="Width (e.g., 1.20)", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="quality",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quality as percentage (0 - 100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="stock_in_mtrs",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Current stock in meters",
                max_digits=12,
            ),
        ),
    ]
