# Generated by Django 5.2.6 on 2025-10-30 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0008_remove_fabric_unit_alter_fabric_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessory",
            old_name="name",
            new_name="item_name",
        ),
        migrations.RemoveField(
            model_name="accessory",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="accessory",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="accessory",
            name="unit",
        ),
        migrations.AddField(
            model_name="accessory",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per unit (numeric)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="accessory",
            name="quality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="accessory",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accessory",
            name="use_in",
            field=models.CharField(
                blank=True,
                help_text="Where this accessory is used (e.g., cushion, bedsheet, etc.)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="printed",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Quantity of fabric consumed (in chosen unit)",
                max_digits=12,
            ),
        ),
    ]
