# Generated by Django 5.2.6 on 2025-10-31 11:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0009_rename_name_accessory_item_name_and_more"),
        ("vendors", "0002_vendor_address_vendor_email_vendor_mobile_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessory",
            name="size",
        ),
        migrations.AddField(
            model_name="accessory",
            name="base_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="accessory",
            name="item_type",
            field=models.CharField(
                blank=True,
                help_text="Type/category of accessory",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accessory",
            name="stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Current stock in units (or meters if applicable)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="accessory",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width if applicable",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printed",
            name="base_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="printed",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per unit for printed product (falls back to fabric cost if zero)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="printed",
            name="product_type",
            field=models.CharField(
                blank=True,
                help_text="Type/category of printed product",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printed",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="printed",
            name="use_in",
            field=models.CharField(
                blank=True,
                help_text="Intended use (e.g., shirts)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printed",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printeds",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="printed",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width if applicable",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per unit",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="quality",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quality as percentage (0 - 100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="use_in",
            field=models.CharField(
                blank=True,
                help_text="Where this accessory is used (e.g., cushion, bedsheet)",
                max_length=200,
                null=True,
            ),
        ),
    ]
