# Generated by Django 5.2.6 on 2025-11-01 05:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0010_remove_accessory_size_accessory_base_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabric",
            name="fabric_type",
        ),
        migrations.AddField(
            model_name="fabric",
            name="type",
            field=models.CharField(
                blank=True,
                db_column="fabric_type",
                help_text="Type/category of fabric (e.g., cotton, linen)",
                max_length=100,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="quality",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quality as percentage (0 - 100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Quality",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="quality",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quality as percentage (0 - 100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Quality",
            ),
        ),
    ]
