# Generated by Django 5.2.6 on 2025-11-01 10:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0011_remove_fabric_fabric_type_fabric_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printed",
            name="quality",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quality as percentage (0 - 100). Inherited from Fabric if left blank.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Quality",
            ),
        ),
    ]
