# Generated by Django 5.2.6 on 2025-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0012_printed_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text='Quality can be numeric (0 - 100) or textual (e.g., "A1", "Fine").',
                max_length=64,
                null=True,
                verbose_name="Quality",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text='Quality can be numeric (0 - 100) or textual (e.g., "A1", "Fine").',
                max_length=64,
                null=True,
                verbose_name="Quality",
            ),
        ),
        migrations.AlterField(
            model_name="printed",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text='Quality can be numeric (0 - 100) or textual (e.g., "A1"). Inherited from Fabric if left blank.',
                max_length=64,
                null=True,
                verbose_name="Quality",
            ),
        ),
    ]
