# Generated by Django 5.2.6 on 2025-11-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0013_alter_accessory_quality_alter_fabric_quality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="quality_text",
            field=models.CharField(
                blank=True,
                help_text='Optional textual quality/variant (e.g., "wooden").',
                max_length=128,
                null=True,
                verbose_name="Quality (text)",
            ),
        ),
    ]
