# Generated by Django 5.2.6 on 2025-11-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawmaterials", "0014_accessory_quality_text"),
        ("vendors", "0003_alter_vendor_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accessories",
                to="vendors.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fabrics",
                to="vendors.vendor",
            ),
        ),
    ]
