# Generated by Django 5.2.6 on 2025-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("Fabric", "Fabric"),
                            ("Accessories", "Accessories"),
                            ("Print", "Print"),
                        ],
                        max_length=32,
                    ),
                ),
                ("product", models.CharField(max_length=200)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate per unit", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
