# Generated by Django 5.2.6 on 2025-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vendor",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_name",
            field=models.CharField(default="Unknown Vendor", max_length=200),
            preserve_default=False,
        ),
    ]
