# Generated by Django 5.2.6 on 2025-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_address_vendor_email_vendor_mobile_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Fabric", "Fabric"),
                    ("Accessories", "Accessories"),
                    ("Print", "Print"),
                    ("Dyeing", "Dyeing"),
                ],
                max_length=32,
            ),
        ),
    ]
