# Generated by Django 5.2.6 on 2025-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[("P", "Percentage"), ("F", "Fixed Amount")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cost Component",
                "verbose_name_plural": "Cost Components",
                "ordering": ["-updated_at", "name"],
            },
        ),
    ]
