# Generated by Django 5.2.6 on 2025-10-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcomponent",
            name="inventory_category",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("FABRIC", "Fabric"),
                    ("ACCESSORY", "Accessory"),
                    ("PRINTED", "Printed"),
                ],
                default="NONE",
                help_text="Choose the inventory category first (Fabric / Accessory / Printed).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="costcomponent",
            name="inventory_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components_inventory_ct",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="costcomponent",
            name="inventory_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
