# Generated by Django 5.2.6 on 2025-10-30 11:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_costcomponent_inventory_category_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name for this component",
                        max_length=200,
                    ),
                ),
                (
                    "inventory_category",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("FABRIC", "Fabric"),
                            ("ACCESSORY", "Accessory"),
                            ("PRINTED", "Printed"),
                        ],
                        default="NONE",
                        help_text="Select the inventory category (Fabric / Accessory / Printed)",
                        max_length=20,
                    ),
                ),
                (
                    "inventory_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        help_text="Quality / variant of the selected product",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Numeric size / quantity for which the cost will be applied",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-filled cost per unit fetched from inventory (server-calculated).",
                        max_digits=12,
                    ),
                ),
                (
                    "logistics_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage to add on top of base cost (e.g., 10 for 10%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final cost after adding logistics percent. (auto-calculated)",
                        max_digits=14,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_master_inventory_ct",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Master",
                "verbose_name_plural": "Component Masters",
                "ordering": ["-updated_at", "name"],
            },
        ),
    ]
