# Generated by Django 5.2.6 on 2025-10-31 10:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_componentmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentmaster",
            name="final_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final price per unit after adding logistics percent (auto-calculated).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="componentmaster",
            name="price_per_sqfoot",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Computed price per square foot using width and the formula provided.",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="componentmaster",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Width of the product fetched from inventory (assumed in inches unless width_uom set).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="componentmaster",
            name="width_uom",
            field=models.CharField(
                blank=True,
                default="inch",
                help_text="Unit of measure for width (e.g., 'inch', 'cm'). Default is 'inch'.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="final_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final cost after adding logistics percent and multiplying by size. (auto-calculated)",
                max_digits=16,
            ),
        ),
    ]
