# Generated by Django 5.2.6 on 2025-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0004_componentmaster_final_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentmaster",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of the product as fetched from inventory (e.g., 'Solid', 'Printed')",
                max_length=150,
                null=True,
            ),
        ),
    ]
