# Generated by Django 5.2.6 on 2025-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0005_componentmaster_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentmaster",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text="Quality/variant of the selected product. Can be numeric (stored as string) or textual (e.g., 'A1', 'Fine').",
                max_length=64,
                null=True,
            ),
        ),
    ]
