# Generated by Django 5.2.6 on 2025-11-01 12:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0006_alter_componentmaster_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentmaster",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="final_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=16
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="final_price_per_unit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="logistics_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="price_per_sqfoot",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=16
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="quality",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="size",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="width_uom",
            field=models.CharField(blank=True, default="inch", max_length=20),
        ),
    ]
