# Generated by Django 5.2.6 on 2025-11-01 12:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0007_alter_componentmaster_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentmaster",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-filled cost per unit fetched from inventory (server-calculated).",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="final_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final cost after adding logistics percent and multiplying by size. (auto-calculated)",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="final_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final price per unit after adding logistics percent (auto-calculated).",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="logistics_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage to add on top of base cost (e.g., 10 for 10%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="price_per_sqfoot",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Computed price per square foot using width and the formula provided.",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text="Quality / variant of the selected product",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="size",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Numeric size / quantity for which the cost will be applied",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of the product as fetched from inventory (e.g., 'Solid', 'Printed')",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Width of the product fetched from inventory (assumed in inches unless width_uom set).",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="componentmaster",
            name="width_uom",
            field=models.CharField(
                blank=True,
                default="inch",
                help_text="Unit of measure for width (e.g., 'inch', 'cm'). Default is 'inch'.",
                max_length=20,
            ),
        ),
    ]
