# Generated by Django 5.2.6 on 2025-11-15 10:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_alter_componentmaster_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentmaster",
            name="logistics_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Percentage to add on top of base cost (e.g., 10 for 10%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
