# Generated by Django 5.2.6 on 2025-11-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0009_alter_componentmaster_logistics_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Color name (e.g., Red, Angora White)", max_length=120
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive colors are hidden in UI but retained for history.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_master",
                    models.ForeignKey(
                        help_text="The ComponentMaster (quality) this color belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="components.componentmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
                "ordering": ["name"],
                "unique_together": {("component_master", "name")},
            },
        ),
    ]
