# Generated by Django 5.2.6 on 2025-11-06 10:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category_master_new", "0002_remove_categorysize_value"),
        ("components", "0008_alter_componentmaster_cost_per_unit_and_more"),
        ("rawmaterials", "0014_accessory_quality_text"),
        ("size_master", "0005_alter_sizemaster_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Size string (e.g. S, M, L)",
                        max_length=64,
                    ),
                ),
                (
                    "stitching_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "finishing_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "packaging_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("collection", models.CharField(blank=True, max_length=255)),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("final_cost", "Final Cost"),
                            ("price_per_sq_ft", "Price/sq.ft"),
                        ],
                        default="final_cost",
                        max_length=32,
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=12
                    ),
                ),
                (
                    "selected_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("hand_work", models.BooleanField(default=False)),
                ("accessory_quantity", models.PositiveIntegerField(default=0)),
                (
                    "accessory_total_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "new_final_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "shipping_cost_india",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shipping_cost_us",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shipping_cost_europe",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gf_overhead_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "texas_buying_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "texas_retail",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "texas_us_selling_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "us_buying_cost_usd",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "us_wholesale_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costing_sheets",
                        to="rawmaterials.accessory",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_sheets",
                        to="category_master_new.category",
                    ),
                ),
                (
                    "quality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_sheets",
                        to="components.componentmaster",
                    ),
                ),
                (
                    "size_master",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the size master entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="size_master.sizemaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costing Sheet",
                "verbose_name_plural": "Costing Sheets",
                "ordering": ["-created_at"],
            },
        ),
    ]
