# Generated by Django 5.2.6 on 2025-11-07 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing_sheet", "0001_initial"),
        ("size_master", "0005_alter_sizemaster_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costingsheet",
            old_name="finishing_cost",
            new_name="shipping_inr",
        ),
        migrations.RenameField(
            model_name="costingsheet",
            old_name="accessory_total_price",
            new_name="us_wholesale",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="accessory",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="accessory_quantity",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="average",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="gf_overhead_cost",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="hand_work",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="new_final_price",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="packaging_cost",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="price_source",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="selected_price",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="shipping_cost_europe",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="shipping_cost_india",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="shipping_cost_us",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="stitching_cost",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="texas_buying_cost",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="texas_retail",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="texas_us_selling_cost",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="total",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="us_buying_cost_usd",
        ),
        migrations.RemoveField(
            model_name="costingsheet",
            name="us_wholesale_cost",
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="component",
            field=models.CharField(
                blank=True,
                help_text="Component label (from category master)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="gf_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="import_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="new_tariff_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="recip_tariff_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="ship_us_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="texas_buying_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="texas_retail_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="tx_to_us_percent",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="size",
            field=models.CharField(
                blank=True, help_text="Size label (e.g. S, M, L)", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="size_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to size master entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="size_master.sizemaster",
            ),
        ),
    ]
