# Generated by Django 5.2.6 on 2025-11-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "costing_sheet",
            "0002_rename_finishing_cost_costingsheet_shipping_inr_and_more",
        ),
        ("costing_sheet", "0003_alter_costingsheet_category"),
    ]

    operations = []
