# Generated by Django 5.2.6 on 2025-11-07 10:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_master", "0005_remove_categorymaster_europe_retail_and_more"),
        ("components", "0008_alter_componentmaster_cost_per_unit_and_more"),
        ("costing_sheet", "0004_merge_20251107_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="component_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a Component Master (quality). Values are snapshotted on save.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets",
                to="components.componentmaster",
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="final_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final cost snapshot from ComponentMaster (or computed).",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="price_per_sqft",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Price per square foot (snapshotted from ComponentMaster).",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Width (snapshotted from ComponentMaster).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="width_uom",
            field=models.CharField(
                blank=True,
                default="inch",
                help_text="Unit of measure for width (e.g., 'inch', 'cm').",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costing_sheets",
                to="category_master.categorymaster",
            ),
        ),
    ]
