# Generated by Django 5.2.6 on 2025-11-09 12:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing_sheet", "0005_costingsheet_component_master_and_more"),
        ("rawmaterials", "0014_accessory_quality_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional accessory chosen from inventory (snapshot stored).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costing_sheets",
                to="rawmaterials.accessory",
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="accessory_line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of accessory line total (quantity × unit price).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="accessory_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of accessory units used for this costing."
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="accessory_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of accessory price per unit (copied from accessory at save time).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="average",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Average (user-entered numeric value).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="gf_overhead_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="New Final Price + GF% of New Final Price",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="new_final_price",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Auto-calculated: Total + Final Cost",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="shipping_cost_europe",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="shipping_cost_india",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="shipping_cost_us",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="texas_buying_cost",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="texas_retail",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="texas_us_selling_cost",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="total",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Auto-calculated: Total = Final Cost × Average",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="us_buying_cost_usd",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Computed US buying cost in USD using tariffs/imports/ship US rules",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="us_wholesale_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="US Wholesale cost (after wholesale % and factor)",
                max_digits=18,
            ),
        ),
    ]
