# Generated by Django 5.2.6 on 2025-11-11 05:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category_master_new",
            "0004_alter_category_options_alter_categorysize_options",
        ),
        ("costing_sheet", "0006_costingsheet_accessory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to Category Master (New) entry (Name).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="costing_sheets_new",
                to="category_master_new.category",
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="finishing",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot: finishing cost/parameter for selected size.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="packaging",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot: packaging cost/parameter for selected size.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="stitching",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot: stitching cost/parameter for selected size.",
                max_digits=12,
            ),
        ),
    ]
