# Generated by Django 5.2.6 on 2025-11-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category_master_new",
            "0004_alter_category_options_alter_categorysize_options",
        ),
        (
            "costing_sheet",
            "0007_costingsheet_category_new_costingsheet_finishing_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="costingsheet",
            name="collection",
            field=models.CharField(
                blank=True,
                help_text="Collection name (e.g., Solid Color)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="color",
            field=models.CharField(
                blank=True, help_text="Color name (e.g., Angora White)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="costingsheet",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated from Category, Name, Collection, Color, Size",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="costingsheet",
            name="size_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to size master entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="category_master_new.categorysize",
            ),
        ),
    ]
