# Generated by Django 5.2.6 on 2025-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0003_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="packagingstage",
            name="due_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Computed due datetime based on time_limit_hours",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="packagingstage",
            name="time_limit_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time limit in hours assigned for this stage",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="workorder",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="raw",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="shopify_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "Web Orders"),
                    ("shopify", "Shopify"),
                    ("faire", "Faire"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="web",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
