# Generated by Django 5.2.6 on 2025-10-03 07:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("finished_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finishedproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="finishedproductline",
            options={},
        ),
        migrations.RemoveField(
            model_name="finishedproduct",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="finishedproduct",
            name="total_cost_cached",
        ),
        migrations.RemoveField(
            model_name="finishedproduct",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="finishedproductline",
            name="line_cost_cached",
        ),
        migrations.RemoveField(
            model_name="finishedproductline",
            name="quantity_per_unit",
        ),
        migrations.RemoveField(
            model_name="finishedproductline",
            name="unit",
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="total_manufacturing_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="finishedproductline",
            name="line_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="finishedproductline",
            name="qty_per_unit",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="finishedproduct",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("qty_change", models.DecimalField(decimal_places=3, max_digits=14)),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
