# Generated by Django 5.2.6 on 2025-10-27 06:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finished_products", "0002_alter_finishedproduct_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finishedproduct",
            name="description",
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="average",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.000"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="fabric_collection",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="fabric_color_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="fabric_pattern",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="fabric_quality",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="fabric_width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="product_category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=2,
                null=True,
            ),
        ),
         migrations.AlterField(
            model_name='finishedproduct',
            name='sku',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),

    ]
